name: Update Documentation

on:
  workflow_dispatch:
    inputs:
      test_repo:
        description: 'Repository URL to test with'
        required: false
        default: 'https://github.com/CodeBoarding/CodeBoarding'
        type: string
  push:
    branches:
      - master
      - main

jobs:
  update-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Fetch CodeBoarding Documentation
        id: codeboarding
        uses: CodeBoarding/CodeBoarding-GHAction@main
        with:
          repository_url: ${{ github.event.inputs.test_repo || github.repository }}
          output_directory: '.codeboarding'

      - name: Display Action Results
        run: |
          echo "Files created: ${{ steps.codeboarding.outputs.files_created }}"
          echo "Output directory: ${{ steps.codeboarding.outputs.output_directory }}"
          echo "Has changes: ${{ steps.codeboarding.outputs.has_changes }}"

      - name: Check for git changes
        id: git-changes
        run: |
          git add .
          if git diff --staged --quiet; then
            echo "has_git_changes=false" >> $GITHUB_OUTPUT
            echo "No changes detected"
          else
            echo "has_git_changes=true" >> $GITHUB_OUTPUT
            echo "Changes detected"
          fi

      - name: Commit and push changes
        if: steps.git-changes.outputs.has_git_changes == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "docs: update codeboarding documentation

          📚 Documentation Update
          - Files created/updated: ${{ steps.codeboarding.outputs.files_created }}
          - Output directory: ${{ steps.codeboarding.outputs.output_directory }}/
          - Repository analyzed: ${{ github.event.inputs.test_repo || github.repository }}
          
          🤖 Automatically generated by CodeBoarding documentation workflow"
          git push
